--- #YAML:1.0
name:                App-Daemon
version:             0.03
abstract:            Start an Application as a Daemon
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Basename:                0
    File::Pid:                     0
    File::Temp:                    0
    Getopt::Std:                   0
    Log::Log4perl:                 1.0
    Pod::Usage:                    0
    Proc::ProcessTable:            0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
