--- #YAML:1.0
name:               App-Daemon
version:            0.21
abstract:           Start an Application as a Daemon
author:
    - Mike Schilli <m@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:   0
    File::Pid:        0
    File::Temp:       0
    Getopt::Std:      0
    Log::Log4perl:    1.0
    Pod::Usage:       0
    Sysadm::Install:  0.37
    Test::More:       0
resources:
    repository:  http://github.com/mschilli/app-daemon
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
